version: '3.7'
services:
  match:
    image: "thanakijwanavit/match:first"
    volumes:
      - q_data:/app/q
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 100
  merger:
    image: "thanakijwanavit/merger:second"
    volumes:
      - q_data:/app/q
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 100
  monitor:
    image: "thanakijwanavit/monitor:first"
    volumes:
      - q_data:/app/q
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
volumes:
  q_data:
networks:
  overlay:
          ipam:
              driver: default
              config:
                - subnet: "172.28.0.0/16"
